# Build settings
gems:
  - jekyll-paginate
  
# Site settings
title: "Lucy Bloomfield"
description: "My little piece of the internet"

email: hello@luchia.com.au
#blog logo
logo: "/assets/images/lucy.jpg"

# blog cover
cover: "/assets/images/top.jpg"

name: 'Lucy Bloomfield'
author: 'Lucy Bloomfield'
author_image: "/assets/images/lucy.jpg"

paginate:	10

url: "http://luchia.com.au" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@luchiamae'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/luchiamae
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	instagram
#    url:	https://instagram.com/lucy_bloomfield
#    desc:	Instagram
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
