name: "Luchia Bloomfield"
description: "UI/UX designer based out of my backpack. Currently living in Australia while working for a number of different companies, including Security Innovation."

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty

collections:
  blog:
    output: true

sass:
  sass_dir: css
  style: compressed